// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20190719093326_Repository.CoreContext")]
    partial class RepositoryCoreContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(36);

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreateDate");

                    b.Property<Guid?>("CreateUser");

                    b.Property<int>("DelFlag");

                    b.Property<int>("EmplyeeType");

                    b.Property<string>("Gender")
                        .HasMaxLength(4);

                    b.Property<int>("IsVaild");

                    b.Property<DateTime?>("LastDate");

                    b.Property<int>("LoginNum");

                    b.Property<string>("Mail")
                        .HasMaxLength(256);

                    b.Property<string>("OaId")
                        .HasMaxLength(128);

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(128);

                    b.Property<Guid>("OrgId");

                    b.Property<string>("OrgName")
                        .HasMaxLength(128);

                    b.Property<string>("PassStandard")
                        .HasMaxLength(512);

                    b.Property<string>("Password")
                        .HasMaxLength(128);

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<int?>("ShowType");

                    b.Property<string>("UserAccount")
                        .HasMaxLength(36);

                    b.Property<string>("UserName")
                        .HasMaxLength(36);

                    b.HasKey("UserId");

                    b.ToTable("core_tb_user");
                });
#pragma warning restore 612, 618
        }
    }
}
